remove django-autocomplete-light static files
shamanu4/dal_admin_filters pull request #38
Opened 2021-06-28 09:58 UTC by MRoci

Hi everyone,
First of all thank you for efforts into this great project!

That said we recently had compatibility issues updating to recent versions of `django-autocomplete-light`, caused by changes made to static files.
In particular `dal` from 3.7.0 has removed the `autocomplete.init.js` script due to a complete rework of the initialization system, so at the moment trying to load it from `AutocompleteFilter` can cause some requests to fail with 404 or worse if the file is still present as a stale static object can break the widget.

Since all these static assets inherited from `django-autocomplete-light` should be already loaded by `ModelSelect2` widget seems reasonable to remove them from filter's media so that the widget alone can pick the correct ones regardless of the version installed.

2021-06-28 10:03 UTC, xrmx approved these changes

2021-06-29 08:49 UTC, xrmx requested changes
Uhm it looks like there are also other changes needed, I had to update the template to use django.jQuery, forward-fix may need the very same fix but I've removed it altogether locally

2021-06-29 10:42 UTC, MRoci commented
I've updated the PR to use django.jQuery in the template and forward-fix.js.
Now it seems to behave correctly

2021-07-04 10:21 UTC, merged

2021-07-04 10:55 UTC, shamanu4 commented
@MRoci, Thank you for your contribution. 
Your PR was included in the latest release https://pypi.org/project/dal-admin-filters/1.1.0/